/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './logout.component';
import * as i2 from './auth.service';
import * as i3 from '@angular/router';
const styles_LogoutComponent:any[] = ([] as any[]);
export const RenderType_LogoutComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_LogoutComponent,data:{}});
export function View_LogoutComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),4,'div',[['class','col-md-8 col-md-offset-2']],
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(3,0,(null as any),
      (null as any),1,'button',[['class','btn btn-danger']],(null as any),[[(null as any),
          'click']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:i1.LogoutComponent = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.onLogout()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),[' Logout'])),
      (_l()(),i0.ɵted(-1,(null as any),['\n    ']))],(null as any),(null as any));
}
export function View_LogoutComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'app-logout',
      ([] as any[]),(null as any),(null as any),(null as any),View_LogoutComponent_0,
      RenderType_LogoutComponent)),i0.ɵdid(1,49152,(null as any),0,i1.LogoutComponent,
      [i2.AuthService,i3.Router],(null as any),(null as any))],(null as any),(null as any));
}
export const LogoutComponentNgFactory:i0.ComponentFactory<i1.LogoutComponent> = i0.ɵccf('app-logout',
    i1.LogoutComponent,View_LogoutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovbm9kZSBjb2Rlcy9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9hdXRoL2xvZ291dC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovbm9kZSBjb2Rlcy9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9hdXRoL2xvZ291dC5jb21wb25lbnQudHMiLCJuZzovLy9EOi9ub2RlIGNvZGVzL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL2F1dGgvbG9nb3V0LmNvbXBvbmVudC50cy5Mb2dvdXRDb21wb25lbnQuaHRtbCIsIm5nOi8vL0Q6L25vZGUgY29kZXMvc2VlZC1wcm9qZWN0L2Fzc2V0cy9hcHAvYXV0aC9sb2dvdXQuY29tcG9uZW50LnRzLkxvZ291dENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxkaXYgY2xhc3M9XCJjb2wtbWQtOCBjb2wtbWQtb2Zmc2V0LTJcIj5cbiAgICAgICAgPGJ1dHRvbiBjbGFzcz1cImJ0biBidG4tZGFuZ2VyXCIgKGNsaWNrKT1cIm9uTG9nb3V0KClcIj4gTG9nb3V0PC9idXR0b24+XG4gICAgPC9kaXY+IiwiPGFwcC1sb2dvdXQ+PC9hcHAtbG9nb3V0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsOENBQ0k7TUFBQTtNQUFBLHdFQUFzQzthQUFBLG1DQUNsQztNQUFBO1VBQUE7UUFBQTtRQUFBO1FBQStCO1VBQUE7VUFBQTtRQUFBO1FBQS9CO01BQUEsZ0NBQW9EO01BQWdCOzs7b0JDRjVFO01BQUE7Z0NBQUEsVUFBQTtNQUFBOzs7In0=
