/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from './auth/signin.component.ngfactory';
import * as i4 from './auth/signup.component.ngfactory';
import * as i5 from './auth/logout.component.ngfactory';
import * as i6 from './messages/messages.component.ngfactory';
import * as i7 from './auth/authentication.component.ngfactory';
import * as i8 from './app.component.ngfactory';
import * as i9 from '@angular/common';
import * as i10 from '@angular/platform-browser';
import * as i11 from '@angular/http';
import * as i12 from '@angular/forms';
import * as i13 from './errors/error.service';
import * as i14 from './messages/message.service';
import * as i15 from '@angular/router';
import * as i16 from './auth/auth.service';
import * as i17 from './auth/signin.component';
import * as i18 from './auth/signup.component';
import * as i19 from './auth/logout.component';
import * as i20 from './messages/messages.component';
import * as i21 from './auth/authentication.component';
import * as i22 from './messages/message.module';
import * as i23 from './auth/auth.module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.SigninComponentNgFactory,i4.SignupComponentNgFactory,i5.LogoutComponentNgFactory,
              i6.MessagesComponentNgFactory,i7.AuthenticationComponentNgFactory,i8.AppComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,
          i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i9.NgLocalization,i9.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,
          i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
          i0.ɵl,([] as any[])),i0.ɵmpd(4608,i10.DomSanitizer,i10.ɵe,[i9.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i10.DomSanitizer]),i0.ɵmpd(4608,
              i10.HAMMER_GESTURE_CONFIG,i10.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i10.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i10.ɵDomEventsPlugin(p0_0),new i10.ɵKeyEventsPlugin(p1_0),
                    new i10.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i9.DOCUMENT,i9.DOCUMENT,i9.DOCUMENT,i10.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i10.EventManager,i10.EventManager,[i10.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i10.ɵDomSharedStylesHost,i10.ɵDomSharedStylesHost,[i9.DOCUMENT]),
          i0.ɵmpd(4608,i10.ɵDomRendererFactory2,i10.ɵDomRendererFactory2,[i10.EventManager,
              i10.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i10.ɵDomRendererFactory2]),i0.ɵmpd(6144,i10.ɵSharedStylesHost,(null as any),
              [i10.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i10.Meta,i10.Meta,[i9.DOCUMENT]),i0.ɵmpd(4608,
              i10.Title,i10.Title,[i9.DOCUMENT]),i0.ɵmpd(4608,i11.BrowserXhr,i11.BrowserXhr,
              ([] as any[])),i0.ɵmpd(4608,i11.ResponseOptions,i11.BaseResponseOptions,
              ([] as any[])),i0.ɵmpd(5120,i11.XSRFStrategy,i11.ɵb,([] as any[])),i0.ɵmpd(4608,
              i11.XHRBackend,i11.XHRBackend,[i11.BrowserXhr,i11.ResponseOptions,i11.XSRFStrategy]),
          i0.ɵmpd(4608,i11.RequestOptions,i11.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i11.Http,i11.ɵc,[i11.XHRBackend,i11.RequestOptions]),i0.ɵmpd(4608,i12.ɵi,
              i12.ɵi,([] as any[])),i0.ɵmpd(4608,i13.ErrorService,i13.ErrorService,
              ([] as any[])),i0.ɵmpd(4608,i14.MessageService,i14.MessageService,[i11.Http,
              i13.ErrorService]),i0.ɵmpd(4608,i12.FormBuilder,i12.FormBuilder,([] as any[])),
          i0.ɵmpd(5120,i15.ActivatedRoute,i15.ɵf,[i15.Router]),i0.ɵmpd(4608,i15.NoPreloading,
              i15.NoPreloading,([] as any[])),i0.ɵmpd(6144,i15.PreloadingStrategy,
              (null as any),[i15.NoPreloading]),i0.ɵmpd(135680,i15.RouterPreloader,
              i15.RouterPreloader,[i15.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i15.PreloadingStrategy]),i0.ɵmpd(4608,i15.PreloadAllModules,
              i15.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i15.ROUTER_INITIALIZER,
              i15.ɵi,[i15.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i15.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i16.AuthService,i16.AuthService,
              [i11.Http,i13.ErrorService]),i0.ɵmpd(512,i9.CommonModule,i9.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i10.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i15.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i15.ɵg,i15.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i10.ɵc(p0_0,p0_1),i15.ɵh(p1_0)];
              },[[2,i10.NgProbeToken],[2,i0.NgProbeToken],i15.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i10.BrowserModule,i10.BrowserModule,[[3,i10.BrowserModule]]),
          i0.ɵmpd(1024,i15.ɵa,i15.ɵd,[[3,i15.Router]]),i0.ɵmpd(512,i15.UrlSerializer,
              i15.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i15.ChildrenOutletContexts,
              i15.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i15.ROUTER_CONFIGURATION,
              {},([] as any[])),i0.ɵmpd(1024,i9.LocationStrategy,i15.ɵc,[i9.PlatformLocation,
              [2,i9.APP_BASE_HREF],i15.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i9.Location,
              i9.Location,[i9.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i15.ROUTES,
              () => {
                return [[{path:'',redirectTo:'signup',pathMatch:'full'},{path:'signin',
                    component:i17.SigninComponent},{path:'signup',component:i18.SignupComponent},
                    {path:'logout',component:i19.LogoutComponent}],[{path:'',redirectTo:'/messages',
                    pathMatch:'full'},{path:'messages',component:i20.MessagesComponent},
                    {path:'auth',component:i21.AuthenticationComponent,loadChildren:'./auth/auth.module#AuthModule'}]];
              },([] as any[])),i0.ɵmpd(1024,i15.Router,i15.ɵe,[i0.ApplicationRef,i15.UrlSerializer,
              i15.ChildrenOutletContexts,i9.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i15.ROUTES,i15.ROUTER_CONFIGURATION,[2,i15.UrlHandlingStrategy],
              [2,i15.RouteReuseStrategy]]),i0.ɵmpd(512,i15.RouterModule,i15.RouterModule,
              [[2,i15.ɵa],[2,i15.Router]]),i0.ɵmpd(512,i11.HttpModule,i11.HttpModule,
              ([] as any[])),i0.ɵmpd(512,i12.ɵba,i12.ɵba,([] as any[])),i0.ɵmpd(512,
              i12.FormsModule,i12.FormsModule,([] as any[])),i0.ɵmpd(512,i22.MessageModule,
              i22.MessageModule,([] as any[])),i0.ɵmpd(512,i12.ReactiveFormsModule,
              i12.ReactiveFormsModule,([] as any[])),i0.ɵmpd(512,i23.AuthModule,i23.AuthModule,
              ([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovbm9kZSBjb2Rlcy9zZWVkLXByb2plY3QvYXNzZXRzL2FwcC9hcHAubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L25vZGUgY29kZXMvc2VlZC1wcm9qZWN0L2Fzc2V0cy9hcHAvYXBwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
